---

- name: Set OS dependent variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
  tags:
    - monit

- include: "monit.yml"
